services: 
  mysql:
    image: mysql:latest
    restart: always
    ports:
      - "3306:3306"
    environment: 
      MYSQL_ROOT_PASSWORD: brunelle
      MYSQL_DATABASE: node_db
  backend:
    build: ./
    ports: 
      - "3500:3500"

