version: "3"
services: 
  mysql:
    image: mysql:latest
    restart: always
    ports:
      - "3307:3306"
    environment: 
      - "MYSQL_ROOT_PASSWORD=brunelle"
  backend:
    image: node:latest
    build: ./
    ports: 
      - "3500:3500"
